/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newbornairlines;
import java.util.Scanner;
import java.awt.*; 
import javax.swing.*; 
/**
 *
 * @author JRios15_17
 */
public class FIrstClassChoicesGUI extends javax.swing.JFrame {
    FirstClassTickets myTicket=new FirstClassTickets();
    boolean wantsNuts=false;
    boolean wantsCookies=false;
    /**
     * Creates new form EconomyChoicesGUI
     */
    public FIrstClassChoicesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        windowSeatEXLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        wSeatLabel = new javax.swing.JLabel();
        windowSeatTextFiels = new javax.swing.JTextField();
        windowSeatEXLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        reserveButton = new javax.swing.JButton();
        nonWSeatLabel1 = new javax.swing.JLabel();
        cookiesRButton = new javax.swing.JRadioButton();
        nutsRButton = new javax.swing.JRadioButton();
        nonWindowSeatEXLabel1 = new javax.swing.JLabel();
        nonWSeatLabel2 = new javax.swing.JLabel();
        wineTextField = new javax.swing.JTextField();
        windowSeatEXLabel1 = new javax.swing.JLabel();
        windowSeatEXLabel2 = new javax.swing.JLabel();
        windowSeatEXLabel4 = new javax.swing.JLabel();

        windowSeatEXLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        windowSeatEXLabel3.setText("Please enter a Wine");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fill out the Following:");

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel.setText("Name:");

        nameTextField.setText("EX: Joe Exotic");

        wSeatLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        wSeatLabel.setText("Window Seat:");

        windowSeatTextFiels.setText("EX: 5");

        windowSeatEXLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        windowSeatEXLabel.setText("If you desire a window seat than choose seats 0-9 and 41-50");

        exitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        reserveButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        reserveButton.setText("Reserve");
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        nonWSeatLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nonWSeatLabel1.setText("Snacks:");

        cookiesRButton.setText("Cookies");
        cookiesRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookiesRButtonActionPerformed(evt);
            }
        });

        nutsRButton.setText("Nuts");
        nutsRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsRButtonActionPerformed(evt);
            }
        });

        nonWindowSeatEXLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nonWindowSeatEXLabel1.setText("Please Choose 1");

        nonWSeatLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nonWSeatLabel2.setText("Wine:");

        wineTextField.setText("EX: Don Perignon");

        windowSeatEXLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        windowSeatEXLabel1.setText("Please Enter Name");

        windowSeatEXLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        windowSeatEXLabel2.setText("Please enter a Wine");

        windowSeatEXLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        windowSeatEXLabel4.setText("(If no wine enter N/A)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reserveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(wSeatLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(nonWSeatLabel1)
                                    .addComponent(nonWSeatLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(windowSeatEXLabel1))
                                    .addComponent(windowSeatTextFiels, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cookiesRButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(nutsRButton)
                                        .addGap(74, 74, 74)
                                        .addComponent(nonWindowSeatEXLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(windowSeatEXLabel2)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(windowSeatEXLabel4)
                                                .addGap(22, 22, 22))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(windowSeatEXLabel)
                                .addGap(28, 28, 28)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windowSeatEXLabel1))
                .addGap(18, 18, 18)
                .addComponent(windowSeatEXLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wSeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windowSeatTextFiels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nonWSeatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookiesRButton)
                    .addComponent(nutsRButton)
                    .addComponent(nonWindowSeatEXLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nonWSeatLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windowSeatEXLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windowSeatEXLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    
    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        Scanner readNameText=new Scanner(nameTextField.getText());
        Scanner seatNumReadText=new Scanner(windowSeatTextFiels.getText());
        Scanner wineReadText=new Scanner(wineTextField.getText());
        
        int arr[]=new int[50];
        
        myTicket.setName(readNameText.nextLine().trim());
        myTicket.setSeatNum(seatNumReadText.nextInt());
        myTicket.setWine(wineReadText.nextLine().trim());
        if(wantsCookies==true && wantsNuts == false){
            myTicket.setSnacks("Cookies");
        }else if(wantsNuts==true && wantsCookies==false){
            myTicket.setSnacks("Nuts");
        }else if(wantsNuts==true && wantsCookies==true){
            myTicket.setSnacks("Nuts and Cookies");
        }else{
            myTicket.setSnacks("None");
        }
        
        if (arr[myTicket.getSeatNum()] == 1){
            System.out.print("Seat not Available");
         for (int i =0; i<arr.length; i++){
            int hold=arr[i];
            if (hold != 1){
                break;
            }
            System.out.print("Plane full");
         }
        }
        arr[myTicket.getSeatNum()] = 1;
        
        if (myTicket.getSeatNum() <= 10){
            myTicket.setWindowSeat(1);
        } 
        else if(myTicket.getSeatNum() >=41 && myTicket.getSeatNum() <=50){
        myTicket.setWindowSeat(1);
    }else{
            myTicket.setWindowSeat(0);
            }
        //System.out.print(myTicket.display());
        DisplayTicketGUI gui=new DisplayTicketGUI();
        gui.setVisible(true);
        gui.setMyTicket(myTicket);
        
//        JFrame displayTicket=new JFrame("Here is your Tickets Information");
//        JLabel displayTickInfo=new JLabel(myTicket.display());
//        JPanel myPanel=new JPanel();
//        
//        myPanel.add(displayTicket);
//        myPanel.add(displayTickInfo);
//        
//        displayTicket.setSize(500,500);
        
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void cookiesRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookiesRButtonActionPerformed
        wantsCookies=true;
    }//GEN-LAST:event_cookiesRButtonActionPerformed

    private void nutsRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsRButtonActionPerformed
        wantsNuts=true;
    }//GEN-LAST:event_nutsRButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIrstClassChoicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIrstClassChoicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIrstClassChoicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIrstClassChoicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIrstClassChoicesGUI().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton cookiesRButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nonWSeatLabel1;
    private javax.swing.JLabel nonWSeatLabel2;
    private javax.swing.JLabel nonWindowSeatEXLabel1;
    private javax.swing.JRadioButton nutsRButton;
    private javax.swing.JButton reserveButton;
    private javax.swing.JLabel wSeatLabel;
    private javax.swing.JLabel windowSeatEXLabel;
    private javax.swing.JLabel windowSeatEXLabel1;
    private javax.swing.JLabel windowSeatEXLabel2;
    private javax.swing.JLabel windowSeatEXLabel3;
    private javax.swing.JLabel windowSeatEXLabel4;
    private javax.swing.JTextField windowSeatTextFiels;
    private javax.swing.JTextField wineTextField;
    // End of variables declaration//GEN-END:variables
}
